### ISSUE TITLE
v0.9.0 doesn't support ocaml 4.05+

### ISSUE THREAD

**Issue by mroch** [janestreet/posixat#1]
master has a fix for 4.05 support but it hasn't been released. see also https://github.com/ocaml/opam-repository/pull/10528

**Comment by trefis** [comment]
I guess you are talking about https://github.com/janestreet/posixat/commit/0105b8d4e0e48e0742ae61375dfdf63f1ccf5b20 ?

I'll try to do a minor release today or tomorrow.

**Comment by mroch** [comment]
Yep, looks like that's it. Thanks!
